#!/bin/bash -eu
set -o pipefail

# Cleanup data if pipeline run multiple times.
rm -rf "${PIPELINE_FEED_DIR}"/DOFET*.csv.lz4

pushd "${PIPELINE_FEED_DIR}" &> /dev/null

curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET79.csv.lz4' \
    -o DOFET79.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET80.csv.lz4' \
    -o DOFET80.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET81.csv.lz4' \
    -o DOFET81.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET82.csv.lz4' \
    -o DOFET82.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET83.csv.lz4' \
    -o DOFET83.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET84.csv.lz4' \
    -o DOFET84.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET85.csv.lz4' \
    -o DOFET85.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET86.csv.lz4' \
    -o DOFET86.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET87.csv.lz4' \
    -o DOFET87.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET88.csv.lz4' \
    -o DOFET88.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET89.csv.lz4' \
    -o DOFET89.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET90.csv.lz4' \
    -o DOFET90.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET91.csv.lz4' \
    -o DOFET91.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET92.csv.lz4' \
    -o DOFET92.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET93.csv.lz4' \
    -o DOFET93.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET94.csv.lz4' \
    -o DOFET94.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET95.csv.lz4' \
    -o DOFET95.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET96.csv.lz4' \
    -o DOFET96.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET97.csv.lz4' \
    -o DOFET97.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET98.csv.lz4' \
    -o DOFET98.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET99.csv.lz4' \
    -o DOFET99.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET00.csv.lz4' \
    -o DOFET00.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET01.csv.lz4' \
    -o DOFET01.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET02.csv.lz4' \
    -o DOFET02.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET03.csv.lz4' \
    -o DOFET03.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET04.csv.lz4' \
    -o DOFET04.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET05.csv.lz4' \
    -o DOFET05.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET06.csv.lz4' \
    -o DOFET06.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET07.csv.lz4' \
    -o DOFET07.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET08.csv.lz4' \
    -o DOFET08.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET09.csv.lz4' \
    -o DOFET09.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET10.csv.lz4' \
    -o DOFET10.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET11.csv.lz4' \
    -o DOFET11.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET12.csv.lz4' \
    -o DOFET12.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET13.csv.lz4' \
    -o DOFET13.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET14.csv.lz4' \
    -o DOFET14.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET15.csv.lz4' \
    -o DOFET15.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET16.csv.lz4' \
    -o DOFET16.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET17.csv.lz4' \
    -o DOFET17.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET18.csv.lz4' \
    -o DOFET18.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET19.csv.lz4' \
    -o DOFET19.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET20.csv.lz4' \
    -o DOFET20.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/fetal_deaths/DOFET21.csv.lz4' \
    -o DOFET21.csv.lz4

popd &> /dev/null
