#!/bin/bash -eu
set -o pipefail

# Clean up old files from multiple runs.
rm -f "${PIPELINE_TMP_DIR}"/sinasc_converted_*.csv.lz4

"${PIPELINE_BIN_DIR}/sinasc/convert_raw_sinasc.py" \
  --input_folder="${PIPELINE_FEED_DIR}" \
  --output_file_pattern="${PIPELINE_TMP_DIR}/sinasc_converted_#.csv.lz4" \
  --anomaly_codes_csv="${PIPELINE_FEED_DIR}/output_cid.csv" \
  --occupation_codes_csv="${PIPELINE_FEED_DIR}/output_occupation.csv"
