#!/bin/bash -eu
set -o pipefail

# Cleanup data if pipeline run multiple times.
rm -rf "${PIPELINE_FEED_DIR}"/sim_*.csv.lz4

pushd "${PIPELINE_FEED_DIR}" &> /dev/null

curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1979.csv.lz4' \
    -o sim_1979.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1980.csv.lz4' \
    -o sim_1980.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1981.csv.lz4' \
    -o sim_1981.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1982.csv.lz4' \
    -o sim_1982.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1983.csv.lz4' \
    -o sim_1983.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1984.csv.lz4' \
    -o sim_1984.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1985.csv.lz4' \
    -o sim_1985.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1986.csv.lz4' \
    -o sim_1986.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1987.csv.lz4' \
    -o sim_1987.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1988.csv.lz4' \
    -o sim_1988.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1989.csv.lz4' \
    -o sim_1989.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1990.csv.lz4' \
    -o sim_1990.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1991.csv.lz4' \
    -o sim_1991.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1992.csv.lz4' \
    -o sim_1992.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1993.csv.lz4' \
    -o sim_1993.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1994.csv.lz4' \
    -o sim_1994.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1995.csv.lz4' \
    -o sim_1995.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1996.csv.lz4' \
    -o sim_1996.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1997.csv.lz4' \
    -o sim_1997.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1998.csv.lz4' \
    -o sim_1998.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_1999.csv.lz4' \
    -o sim_1999.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2000.csv.lz4' \
    -o sim_2000.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2001.csv.lz4' \
    -o sim_2001.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2002.csv.lz4' \
    -o sim_2002.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2003.csv.lz4' \
    -o sim_2003.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2004.csv.lz4' \
    -o sim_2004.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2005.csv.lz4' \
    -o sim_2005.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2006.csv.lz4' \
    -o sim_2006.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2007.csv.lz4' \
    -o sim_2007.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2008.csv.lz4' \
    -o sim_2008.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2009.csv.lz4' \
    -o sim_2009.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2010.csv.lz4' \
    -o sim_2010.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2011.csv.lz4' \
    -o sim_2011.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2012.csv.lz4' \
    -o sim_2012.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2013.csv.lz4' \
    -o sim_2013.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2014.csv.lz4' \
    -o sim_2014.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2015.csv.lz4' \
    -o sim_2015.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2016.csv.lz4' \
    -o sim_2016.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2017.csv.lz4' \
    -o sim_2017.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2018.csv.lz4' \
    -o sim_2018.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2019.csv.lz4' \
    -o sim_2019.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2020.csv.lz4' \
    -o sim_2020.csv.lz4
curl 'https://zenysis-br-covid-assets.s3.amazonaws.com/integration_trainings/sim/deaths/sim_2021.csv.lz4'\
    -o sim_2021.csv.lz4

popd &> /dev/null
