#!/bin/bash -eu
set -o pipefail

pushd "${PIPELINE_FEED_DIR}" &> /dev/null

"${PIPELINE_BIN_DIR}/shared/convert_cid_csv.py" \
  --input_cid9="cid9.csv" \
  --input_cid10="cid10_flat.csv" \
  --additional_mappings \
    "garbage_code_levels.csv:exact,Package level/Cause level:PrimaryCauseGarbage" \
    "dant_plan_categories.csv:parent,DANT Plan Category:PlanoDant" \
    "alcohol_titles.csv:exact,Alcohol Cause of Death:AlcoholCauseOfDeath" \
    "mother_mortality.csv:parent,MotherMortality:MotherMortality" \
  --output_file="output_cid.csv"

popd &> /dev/null
