#!/bin/bash -eu
set -o pipefail

# Cleanup data if pipeline run multiple times.
rm -rf "${PIPELINE_FEED_DIR}"/sinasc_*.csv.lz4

pushd "${PIPELINE_FEED_DIR}" &> /dev/null

for year in {1996..2020}; do
    curl "https://diaad.s3.sa-east-1.amazonaws.com/sinasc/SINASC_${year}.csv"\
        | iconv -f ISO-8859-1 -t UTF-8//TRANSLIT \
        | lz4 -9 \
        > "sinasc_${year}.csv.lz4"
done

popd &> /dev/null
